In [1]:
import tensorflow as tf

# 常量
data1 = tf.constant(2.5)
# 变量
data2 = tf.Variable(10, name='var')
# 打印数据的描述信息
print(data1)
print(data2)

Tensor("Const:0", shape=(), dtype=float32)
<tf.Variable 'var:0' shape=() dtype=int32_ref>


In [2]:
sess = tf.Session()
print(sess.run(data1))
# 报错, 需要使用session 进行初始化
# print(sess.run(data2))
init = tf.global_variables_initializer()
sess.run(init)
print(sess.run(data2))
sess.close()


2.5
10


In [3]:
# 本质： tensorflow = tensor +  graphs(计算图)
# tensor 本质数据
# op => operation 操作, 赋值或者四则运算
# graphs 数据操作
# 所有都要放到session中执行, session是核心
# 使用with关键字
init = tf.global_variables_initializer()
sess = tf.Session()
with sess:
    sess.run(init)
    print(sess.run(data2))

10


In [4]:
# 常量运算
data1 = tf.constant(6)
data2 = tf.constant(2)
dataAdd = tf.add(data1,data2)
dataMul = tf.multiply(data1,data2)
dataSub = tf.subtract(data1,data2)
dataDiv = tf.divide(data1,data2)
with tf.Session() as sess:
    print(sess.run(dataAdd))
    print(sess.run(dataMul))
    print(sess.run(dataSub))
    print(sess.run(dataDiv))
print("end!")

8
12
4
3.0
end!


In [5]:
# 变量运算
data1 = tf.constant(6)
data2 = tf.Variable(2)
# 加减乘除
dataAdd = tf.add(data1,data2)
#  将dataAdd 运算得到的值赋值给data2
dataCopy = tf.assign(data2, dataAdd)
dataMul = tf.multiply(data1,data2)
dataSub = tf.subtract(data1,data2)
dataDiv = tf.divide(data1,data2)
# 初始化
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(dataAdd))
    print(sess.run(dataMul))
    print(sess.run(dataSub))
    print(sess.run(dataDiv))

    print("test dataCopy")
    print("sess.run(dataCopy)", sess.run(dataCopy))
    print("dataCopy.eval()", dataCopy.eval())
    print("tf.get_default_session()", tf.get_default_session().run(dataCopy))
print("end!")

8
12
4
3.0
test dataCopy
sess.run(dataCopy) 8
dataCopy.eval() 14
tf.get_default_session() 20
end!


In [ ]:
# placeholder 实时插入数据
data1 = tf.placeholder(tf.float32)
data2 = tf.placeholder(tf.float32)

dataAdd = tf.add(data1, data2)
with tf.Session() as sess:
    # 第一个参数是运算结果, 第二参数是 (feed_dict = {value1:value, value:value})
    print(sess.run(dataAdd, feed_dict={data1: 6, data2: 2}))
print("end")

In [ ]:
data1 = tf.constant([[6,6]])
data2 = tf.constant([[2],
                    [2]])
data3 = tf.constant([[3,3]])
data4 = tf.constant([[1,2],
                    [3,4],
                    [5,6]])
matMul_1_2 = tf.matmul(data1, data2)

matMul_2_1 = tf.matmul(data2, data1)

matAdd = tf.add(data1, data3)

print(data4.shape)

with tf.Session() as sess:
    # 打印整体
    print(sess.run(data4))
    # 打印一行
    print(sess.run(data4[0]))
    # 打印一列
    print(sess.run(data4[:,0]))
    # 打印第一行，第一列
    print(sess.run(data4[0,0]))
    # 矩阵乘法
    print(sess.run(matMul_1_2))
    print(sess.run(matMul_2_1))
    # 矩阵加法
    print(sess.run(matAdd))
    print(sess.run([matMul_1_2, matMul_2_1]))

In [ ]:
mat_0 = tf.constant([[0, 0, 0], [0, 0, 0]])
# 全0
mat_1 = tf.zeros([2, 3])
# 全1
mat_2 = tf.ones([3, 2])
# 全指定值
mat_3 = tf.fill([2, 3], 15)
with tf.Session() as sess:
    print(sess.run(mat_0))
    print(sess.run(mat_1))
    print(sess.run(mat_2))
    print(sess.run(mat_3))

In [ ]:
mat_1 = tf.constant([[2], [3], [4]])
mat_2 = tf.zeros_like(mat_1)
mat_3 = tf.linspace(0.0, 2.0, 11)
# 随机矩阵
mat_4 = tf.random_uniform([2,3],-1,2)
with tf.Session() as sess:
    print(sess.run(mat_1))
    print(sess.run(mat_2))
    print(sess.run(mat_3))
    print(sess.run(mat_4))

8.0
end


In [9]:
data1 = tf.constant([[6,6]])
data2 = tf.constant([[2],
                    [2]])
data3 = tf.constant([[3,3]])
data4 = tf.constant([[1,2],
                    [3,4],
                    [5,6]])
matMul_1_2 = tf.matmul(data1, data2)

matMul_2_1 = tf.matmul(data2, data1)

matAdd = tf.add(data1, data3)

print(data4.shape)

with tf.Session() as sess:
    # 打印整体
    print(sess.run(data4))
    # 打印一行
    print(sess.run(data4[0]))
    # 打印一列
    print(sess.run(data4[:,0]))
    # 打印第一行，第一列
    print(sess.run(data4[0,0]))
    # 矩阵乘法
    print(sess.run(matMul_1_2))
    print(sess.run(matMul_2_1))
    # 矩阵加法
    print(sess.run(matAdd))
    print(sess.run([matMul_1_2, matMul_2_1]))

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 2]
[1 3 5]
1
[[24]]
[[12 12]
 [12 12]]
[[9 9]]
[array([[24]]), array([[12, 12],
       [12, 12]])]


In [12]:
mat_0 = tf.constant([[0, 0, 0], [0, 0, 0]])
# 全0
mat_1 = tf.zeros([2, 3])
# 全1
mat_2 = tf.ones([3, 2])
# 全指定值
mat_3 = tf.fill([2, 3], 15)
with tf.Session() as sess:
    print(sess.run(mat_0))
    print(sess.run(mat_1))
    print(sess.run(mat_2))
    print(sess.run(mat_3))

[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[15 15 15]
 [15 15 15]]


In [14]:
mat_1 = tf.constant([[2], [3], [4]])
mat_2 = tf.zeros_like(mat_1)
mat_3 = tf.linspace(0.0, 2.0, 11)
# 随机矩阵
mat_4 = tf.random_uniform([2,3],-1,2)
with tf.Session() as sess:
    print(sess.run(mat_1))
    print(sess.run(mat_2))
    print(sess.run(mat_3))
    print(sess.run(mat_4))

[[2]
 [3]
 [4]]
[[0]
 [0]
 [0]]
[0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001 2.       ]
[[ 0.7946317  1.4028666  1.9227102]
 [ 1.7258863 -0.6720731  1.0476704]]
